#!/usr/bin/env bash

declare ROOT="/lustre/scratch118/humgen/hgi/projects/hgi_vault_dev/scratch123"
declare BINARY="$(basename "$0")"

source "${ROOT}/hgi_vault_env/bin/activate"

export VAULTRC="${ROOT}/etc/vaultrc"
exec "${BINARY}" "$@"
